<?php
/**
 * Partial
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
?>

<div id="copyrightInfo">

    <div id="copyrightInner">

        <div id="copyrightLink">
            <?php
            echo $this->codeBlender();
            ?>
        </div>

        <div id="copyrightTitle">
            &copy; <?php echo date('Y'); ?> Triangle Solutions Ltd - All Rights Reserved
        </div>

        <ul id="copyrightList">

            <li>
                <a href="http://www.triangle-solutions.com/" title="Triangle Solutions Ltd">A Triangle Solutions Ltd Production</a>
            </li>

            <li class="noBorder"><a href="/core/contact" title="Contact Triangle">Contact Us</a></li>

        </ul>

        <div class="clear"></div>

    </div>

</div>
