<?php
/**
 * Partial
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
?>

<ul class="tabs">

    <?php
    // Translation
    $translate = Zend_Registry::get('Zend_Translate');

    // Loop through the container
    foreach ($this->container as $page) {

        // Check whether the page is set as Visible and also it is accepted through the ACL
        if ($page->isVisible() && $this->navigation()->accept($page) && (!$page->topmenu || $page->topmenu === 'both')) {

            // Create the class to use if the tab is active
            $liClass = $page->isActive(false) ? ' class="active"' : '';
            ?>

            <li<?php echo $liClass; ?>>
                <a href="<?php echo $page->getHref(); ?>" title="<?php echo $translate->_($page->getTitle()); ?>">
                    <span><?php echo $translate->_($page->getLabel()); ?></span></a>
            </li>

            <?php
        }
    }
    ?>

</ul>
