<?php
/**
 * Partial
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2000-2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
?>

<ul>

    <li>
        Of all the applications I use for business, iChitty is the most important and easiest to use.
        <span>Drop Web Solutions, Sussex UK.</span>
    </li>

    <li>
        I now find it so easy to stay on top of my company finances. 10 minutes each day to simply breeze through my
        invoices.
        <span>Beeptaxi, London UK</span>
    </li>

    <li>
        Having an online solution makes iChitty the way forward. When I am travelling I can still log invoices. Check
        the status and add important notes for my staff to follow up on. Brilliant!
        <span>Linax Inc, PA, USA</span>
    </li>

</ul>

<div style="border-top: 1px solid #000000; border-bottom: 1px solid #1E1E1E; margin: 20px 0;"></div>

<img style="float: left; margin-right: 16px;"
     src="<?php echo $this->themePath ?>/images/template/commentIcon.png"
     height="48" width="48" alt="Comment" title="Comment" />

<h3>Tell us what you think!</h3>

<p>
    Please consider taking a few moments to tell us what you think about this site. We are always
    developing our services, and would really appreciate your thoughts and suggestions; including improvements
    and features you would like to see. In fact, any feedback is welcome!
</p>

<br />

<p>
    If you have a question then please use our <a href="/core/contact" title="Contact Us">Contact Form</a>.
</p>
