<?php
/**
 * Layout
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
// Config
$config = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOptions();

// DocType
echo $this->doctype('XHTML5');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#" xmlns:og="http://ogp.me/ns#">

    <head>

        <?php
        // Header
        try {
            $this->header();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }

        // Page Title
        echo $this->headTitle($this->title);

        // Content Type
        echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');

        // Facebook Open Graph Meta Tags
        if ($this->ogDescription) {
            try {
                echo $this->facebook_OpenGraph();
            } catch (Exception $e) {
                echo 'Failed: ' . $e->getMessage();
            }
        }

        // Google Verification line if a valid entry is in the configuration
        if (!empty($config['google']['siteVerification'])) {
            $this->headMeta()->setName('google-site-verification', $config['google']['siteVerification']);
        }

        // Prepend the Core Theme style sheet
        echo $this->headLink()
            ->prependStylesheet($this->cssPath . '/default.css', 'screen')
            ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'), 'PREPEND');

        // Print the head links which can contain Javascript references
        echo $this->headStyle();
        echo $this->headScript();

        // Get Satisfaction
        try {
            if (!empty($config['getSatisfaction']['on'])) {
                echo $this->getSatisfaction();
            }
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>
    </head>

    <body>

        <?php
        // Facebook JS SDK Helper
        try {
            echo $this->facebook_JavascriptSDK();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <?php
        // Google analytics
        try {
            if (!empty($config['google']['analytics'])) {
                echo $this->google_Analytics();
            }
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <div id="wrap">

            <a name="top"></a>

            <div id="head">

                <?php
                try {

                    // Top Navigation
                    echo $this->navigation()->menu()->setPartial(array('partial/topmenu.phtml', 'default'));

                    // Tab Navigation
                    echo $this->navigation()->menu()->setPartial(array('partial/menu.phtml', 'default'));
                } catch (Exception $e) {
                    Zend_Debug::dump($e);
                }

                // Google Search
                if (!empty($config['google']['Cx'])) {

                    try {
                        echo '<div id="googleSearch">' . $this->google_Search() . '</div>';
                    } catch (Exception $e) {
                        echo 'Failed: ' . $e->getMessage();
                    }
                }
                ?>

            </div>

            <?php
            // Main Layout Content
            try {
                echo $this->layout()->content;
            } catch (Exception $e) {
                echo 'Failed: ' . $e->getMessage();
            }
            ?>

            <div id="footerClear"></div>

        </div>

        <?php
        // Footer Partial
        try {
            echo $this->render('partial/footer.phtml');
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }

        // Copyright Partial
        try {
            echo $this->render('partial/copyright.phtml');
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

    </body>

</html>
