<?php
/**
 * Layout
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
// Config
$config = Zend_Controller_Front::getInstance()->getParam('bootstrap')->getOptions();

// Create the DocType as Strict
echo $this->doctype('XHTML5');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
    <head>

        <?php
        // Add in the Page Title
        echo $this->headTitle($this->title);

        // Set the correct content type
        echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');

        // Create the Facebook Meta Tags required
        if ($this->ogDescription) {
            ?>
            <meta property="og:description" content="<?php echo $this->ogDescription; ?>" />
            <meta property="og:image" content="<?php echo $this->imagePath . $this->ogImage; ?>" />
            <meta property="og:site_name" content="Triangle Solutions" />
            <meta property="og:title" content="<?php echo $this->ogTitle; ?>" />
            <meta property="og:type" content="article" />
            <meta property="og:url" content="<?php echo $this->ogURL; ?>" />
            <meta property="fb:app_id" content="<?php echo $config['facebook']['appID']; ?>" />
            <?php
        }

        // Set the Google Verification line if a valid entry is in the configuration
        if (!empty($config['google']['siteVerification'])) {
            $this->headMeta()->setName('google-site-verification', $config['google']['siteVerification']);
        }

        // Prepend the Core Theme style sheet
        echo $this->headLink()
            ->prependStylesheet($this->themePath . '/default/css/default.css', 'screen')
            ->prependStylesheet($this->cssPath . '/main.css', 'screen')
            ->headLink(array('rel' => 'favicon', 'href' => '/favicon.ico'), 'PREPEND');

        // Print the head links which can contain Javascript references
        echo $this->headStyle();
        echo $this->headScript();

        // Check to see in the configuration if the site requires Get Satisfaction to be added
        try {
            if (!empty($config['getSatisfaction']['on'])) {
                echo $this->feedBack_GetSatisfaction();
            }
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>
    </head>
    <body>

        <?php
        // Facebook SDK Helper
        try {
            echo $this->facebook_JavascriptSDK();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <?php
        // Add in Google analytics if required
        try {

            if (!empty($config['google']['analytics'])) {
                echo $this->google_Analytics();
            }
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <div id="wrap">

            <a name="top"></a>

            <div id="head">
                <?php
                try {

                    // Add the top menu navigation
                    echo $this->navigation()->menu()->setPartial(array('topmenu.phtml', 'default'));

                    // Add the tab navigation
                    echo $this->navigation()->menu()->setPartial(array('menu.phtml', 'default'));
                } catch (Exception $e) {
                    Zend_Debug::dump($e);
                }
                ?>
                <div id="googleSearch">
                    <?php
                    // Add the Google Search element
                    if (!empty($config['google']['Cx'])) {

                        try {
                            echo $this->google_Search();
                        } catch (Exception $e) {
                            echo 'Failed: ' . $e->getMessage();
                        }
                    }
                    ?>
                </div>
            </div>
            <?php
            // Add the main Layout content
            try {
                echo $this->layout()->content;
            } catch (Exception $e) {
                echo 'Failed: ' . $e->getMessage();
            }
            ?>
            <div class="clear"></div>
        </div>

        <div id="footer">
            <div id="footerInner">
                <?php
                // Renders the Footer Partial from the default Module
                try {
                    echo $this->render('footer.phtml');
                } catch (Exception $e) {
                    echo 'Failed: ' . $e->getMessage();
                }
                ?>
            </div>
        </div>

        <div id="copyrightInfo">
            <div id="copyrightInner">
                <?php
                // Renders the Copyright Partial from the default Module
                try {
                    echo $this->render('copyright.phtml');
                } catch (Exception $e) {
                    echo 'Failed: ' . $e->getMessage();
                }
                ?>
                <div class="clear"></div>
            </div>
        </div>

    </body>

</html>
