<?php
/**
 * Layout
 *
 * @category  CodeBlender
 * @package   Theme
 * @copyright Copyright (c) 2011 Triangle Solutions Ltd. (http://www.triangle-solutions.com/)
 * @license   http://codeblender.net/license
 */
// Create the Doctype as Strict
echo $this->doctype('HTML5');
?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
    <head>

        <?php
        // Header
        try {
            $this->header();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }

        // Charset
        echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');

        // Title
        echo $this->headTitle($this->title);

        // Stylesheet - Favicon
        echo $this->headLink()
            ->appendStylesheet($this->cssPath . '/admin.css', 'screen')
            ->headLink(array('rel' => 'favicon', 'href' => $this->imagePath . '/favicon.ico'), 'PREPEND');

        // JQuery
        try {
            echo $this->google_AjaxLibraries(array(
                'library' => 'jquery',
                'version' => 1
            ));
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }

        echo $this->headStyle();
        echo $this->headScript()->appendFile($this->jsPath . '/main.js', 'text/javascript');
        ?>

    </head>
    <body class="login">

        <?php
        // Facebook SDK Helper
        try {
            echo $this->facebook_JavascriptSDK();
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

        <div id="wrapper">

            <div id="header">
                <h1><?php echo $this->siteTitle; ?></h1>
            </div>

            <div id="info">
            </div>

            <div id="content">

                <div id="mainContent">
                    <?php echo $this->layout()->content; ?>
                </div>

                <div class="clear"></div>

            </div>

        </div>

        <?php
        try {
            echo $this->render('footer.phtml');
        } catch (Exception $e) {
            echo 'Failed: ' . $e->getMessage();
        }
        ?>

    </body>

</html>
